### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by aronbeal** [nLight/Phing#4]
Hi, would like to extend this code for my own purposes; I need a version that will prompt for an RSA cert password upon launch.  What license are you releasing this under?

**Comment by nLight** [comment]
Hello Aron!

You can use this code under MIT License.

## 

С уважением, Рожков Дмитрий

**Comment by aronbeal** [comment]
Great, thanks!

**Comment by aronbeal** [comment]
(extremely belatedly). :)
